spring:
  application:
    name: rambling-admin

server:
  port: ${PORT:8000}

eureka:
  server:
    hostname: ${EUREKAHOST:localhost}
  client:
    service-url:
      default-zone: http://${eureka.server.hostname}/eureka
